[tools]
node = "latest"
pnpm = "latest"
bun = "latest"
deno = "latest"
aws = "latest"
"npm:@antfu/ni" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
"npm:vercel" = "latest"
